services:
  frontend:
    build: ./Frontend
    image: vashista/resumeforge-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mern-net

  backend:
    build: ./resumeforge-backend
    image: vashista/resumeforge-backend:latest
    ports:
      - "5000:5000"
    networks:
      - mern-net

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - mern-net

volumes:
  mongo-data:

networks:
  mern-net:
